### ISSUE TITLE
Pouvoir affecter un groupe demandeur pour affecter la saisonnalité

### ISSUE THREAD

**Issue by Jm0u** [InfotelGLPI/seasonality#1]
Pouvoir affecter un groupe demandeur pour affecter la saisonnalité

**Comment by tsmr** [comment]
Je n'ai pas bien compris le besoin. Tu souhaite affecter un groupe selon une saisonnalité ? Exemple Groupe 1 du 01/01 au 01/06 et Groupe 2 du 01/06 au 31/12 ?

**Comment by Jm0u** [comment]
Je te donne un exemple 
Un demandeur X faisant partie du groupe Y fait une demande du 08/09 au 18/09
Je voudrais automatiquement que ce ticket soit modifié en conséquence au niveau de l'urgence

**Comment by tsmr** [comment]
Donc ajouter de la saisonnalité sur les groupes / utilisateurs. OK
